<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE event [<!ELEMENT zip_code (#PCDATA)><!ELEMENT url_link_display (#PCDATA)><!ELEMENT url (#PCDATA)><!ELEMENT tracks (track+)><!ELEMENT track (#PCDATA)><!ELEMENT title (#PCDATA)><!ELEMENT timeslot (slot_id?, title, room, date, start_time, end_time, description?, acm_doi?, persons?, tracks?, tags?)><!ELEMENT tags (tag+)><!ELEMENT tag (#PCDATA)><!ELEMENT suffix (#PCDATA)><!ELEMENT subevent_logo_url (#PCDATA)><!ELEMENT subevent_id (#PCDATA)><!ELEMENT subevent (subevent_id?, title, acronym?, subevent_type, description?, room, date, url?, url_link_display?, subevent_logo_url?, acm_doi?, persons?, tracks?, tags?, sponsor?, timeslot*)><!ELEMENT state (#PCDATA)><!ELEMENT start_time (#PCDATA)><!ELEMENT start_date (#PCDATA)><!ELEMENT sponsor (#PCDATA)><!ELEMENT sort_key (#PCDATA)><!ELEMENT slot_id (#PCDATA)><!ELEMENT subevent_type EMPTY><!ATTLIST subevent_type	type (case_study | demonstration | poster | regular | tutorial | workshop) #IMPLIED><!ELEMENT room (#PCDATA)><!ELEMENT role (#PCDATA)><!ELEMENT picture_url (#PCDATA)><!ELEMENT persons (person+)><!ELEMENT person (role, sort_key, first_name, middle_name?, last_name, suffix?, affiliation, acm_profile_id?, email?, bio?, homepage_url?, picture_url?)><!ELEMENT middle_name (#PCDATA)><!ELEMENT location (facility_name, facility_map_url?, address, city, state?, country, zip_code?)><!ELEMENT last_name (#PCDATA)><!ELEMENT homepage_url (#PCDATA)><!ELEMENT first_name (#PCDATA)><!ELEMENT facility_name (#PCDATA)><!ELEMENT facility_map_url (#PCDATA)><!ELEMENT event_type EMPTY><!ATTLIST event_type	type (conference|workshop|symposium) #IMPLIED><!ELEMENT event (event_details, subevent*, timeslot*)><!ELEMENT event_logo_url (#PCDATA)><!ELEMENT event_details (title, acronym, event_type, start_date, end_date, location, description, url?, url_link_display?, event_logo_url?, persons?)><!ELEMENT end_time (#PCDATA)><!ELEMENT end_date (#PCDATA)><!ELEMENT email (#PCDATA)><!ELEMENT description (#PCDATA)><!ELEMENT date (#PCDATA)><!ELEMENT country (#PCDATA)><!ELEMENT city (#PCDATA)><!ELEMENT bio (#PCDATA)><!ELEMENT affiliation (#PCDATA)><!ELEMENT address (#PCDATA)><!ELEMENT acronym (#PCDATA)><!ELEMENT acm_profile_id (#PCDATA)><!ELEMENT acm_doi (#PCDATA)>]>
<event>
  <event_details>
    <title>ICFP 2016</title>
    <acronym>ICFP 2016</acronym>
    <event_type type="conference"/>
    <start_date>2016/09/18</start_date>
    <end_date>2016/09/24</end_date>
    <location>
      <facility_name>Nara Kasugano International Forum</facility_name>
      <address>101 Kasugano</address>
      <city>Nara</city>
      <country>Japan</country>
    </location>
    <description>ICFP 2016 is the 21st ACM SIGPLAN International Conference on Functional Programming.
ICFP provides a forum for researchers and developers to hear about the latest work on the design, implementations, principles, and uses of functional programming. The conference covers the entire spectrum of work, from practice to theory, including its peripheries.
During the conference there will be a Student Research Competition for Graduate and Undergraduate students. Submission deadline: August 3rd, 2016.
Prior to the conference the ICFP Programming Contest will be held from August 5 to August 8.
During the whole ICFP week, the venue will be open from 8:30am for organizers and 8:45am for participants.
Here is a PDF version of the paper program.
The full proceedings of ICFP and workshops can be downloaded here. Please lookup id and password as the registration desk.
Individual paper links are also available from programs on this site.</description>
    <url>http://conf.researchr.org/home/icfp-2016</url>
    <url_link_display>ICFP 2016</url_link_display>
    <persons>
      <person>
        <role>Program Chair in Organizing Committee, ICFP'16 Program Chair in Steering Committee</role>
        <sort_key>1</sort_key>
        <first_name>Eijiro</first_name>
        <last_name>Sumii</last_name>
        <affiliation>Tohoku University</affiliation>
        <bio>Professor in Graduate School of Information Sciences, Tohoku University from May 2014. Main interest includes the theory and applications of programming languages and type systems in a variety of domains including process calculi, partial evaluation, security foundations, and functional programming.</bio>
        <homepage_url>http://www.kb.ecei.tohoku.ac.jp/~sumii/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/eijirosumii/80a91b58-b657-4288-90f2-a5d5986f7774/small.jpg</picture_url>
      </person>
      <person>
        <role>Video Co-Chair in Organizing Committee</role>
        <sort_key>2</sort_key>
        <first_name>Jose</first_name>
        <last_name>Calderon</last_name>
        <affiliation>Galois</affiliation>
        <bio>undefined</bio>
        <picture_url>http://conf.researchr.org/getProfileImage/josecalderon/e4e6ac0b-3f3d-4388-b08d-ee21e3ef5511/small.jpg</picture_url>
      </person>
      <person>
        <role>ICFP'14 Program Chair in Steering Committee</role>
        <sort_key>3</sort_key>
        <first_name>Manuel</first_name>
        <last_name>Chakravarty</last_name>
        <affiliation>University of New South Wales</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cse.unsw.edu.au/~chak/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/manuelchakravarty/12c6a408-4abc-4eb8-9d4b-c4627f17a326/small.jpg</picture_url>
      </person>
      <person>
        <role>Video Chair in Organizing Committee</role>
        <sort_key>4</sort_key>
        <first_name>Iavor</first_name>
        <last_name>Diatchki</last_name>
        <affiliation>Galois, Inc.</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://galois.com/team/iavor-diatchki/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/iavordiatchki1/a98c116d-b41d-4fac-96cb-c83ce3a61d28/small.jpg</picture_url>
      </person>
      <person>
        <role>ICFP'18 General Chair in Steering Committee</role>
        <sort_key>5</sort_key>
        <first_name>Robby</first_name>
        <last_name>Findler</last_name>
        <affiliation>Northwestern University</affiliation>
        <bio>robby@eecs.northwestern.edu</bio>
        <homepage_url>http://www.eecs.northwestern.edu/~robby/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/robbyfindler/28e677e8-d52c-40d1-841d-4b2774afecd1/small.jpg</picture_url>
      </person>
      <person>
        <role>ICFP'15 General Chair in Steering Committee</role>
        <sort_key>6</sort_key>
        <first_name>Kathleen</first_name>
        <last_name>Fisher</last_name>
        <affiliation>Tufts University</affiliation>
        <bio>Kathleen Fisher is Professor in the Computer Science Department at Tufts. Previously, she was a Principal Member of the Technical Staff at AT&amp;amp;T Labs Research, a Consulting Faculty Member in the Computer Science Department at Stanford University, and a program manager at DARPA where she started and managed the HACMS and PPAML programs. Kathleen’s research focuses on advancing the theory and practice of programming languages and on applying ideas from the programming language community to the problem of ad hoc data management. The main thrust of her work has been in domain-specific languages to facilitate programming with massive amounts of ad hoc data, including the Hancock system for efficiently building signatures from massive transaction streams and the PADS system for managing ad hoc data. Recently, she has been exploring synergies between machine learning and programming languages and studying how to apply advances in programming languages to the problem of building more secure systems.
Kathleen is an ACM Fellow. She has served as program chair for FOOL, ICFP, CUFP, and OOPSLA and as General Chair for ICFP 2015. Kathleen is past Chair of the ACM Special Interest Group in Programming Languages (SIGPLAN), past Co-Chair of CRA’s Committee on the Status of Women (CRA-W), and a former editor of the Journal of Functional Programming. She is an Associate Editor for TOPLAS.</bio>
        <homepage_url>http://www.cs.tufts.edu/~kfisher</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/kathleenfisher/04a1b289-f7fe-4e91-b686-6b34a7a45cb2/small.jpg</picture_url>
      </person>
      <person>
        <role>ICFP'18 Program Chair in Steering Committee</role>
        <sort_key>7</sort_key>
        <first_name>Matthew</first_name>
        <last_name>Flatt</last_name>
        <affiliation>University of Utah</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.utah.edu/~mflatt/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/matthewflatt/61fb7ec4-16ed-42de-bbc5-597943a6c87e/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Volunteer Co-Chair in Organizing Committee</role>
        <sort_key>8</sort_key>
        <first_name>Yosuke</first_name>
        <last_name>Fukuda</last_name>
        <affiliation>Kyoto University</affiliation>
        <bio>undefined</bio>
      </person>
      <person>
        <role>General Co-Chair in Organizing Committee</role>
        <sort_key>9</sort_key>
        <first_name>Jacques</first_name>
        <last_name>Garrigue</last_name>
        <affiliation>Nagoya University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.math.nagoya-u.ac.jp/~garrigue/home.html</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/jacquesgarrigue1/1c6cff5e-3103-4182-96a0-04ceeb96bf14/small.jpg</picture_url>
      </person>
      <person>
        <role>ICFP'16 General Chair in Steering Committee</role>
        <sort_key>10</sort_key>
        <first_name>Jacques</first_name>
        <last_name>Garrigue</last_name>
        <affiliation>Nagoya University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.math.nagoya-u.ac.jp/~garrigue/home.html</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/jacquesgarrigue/bec96eef-5450-49a7-b90f-669ca609e0c7/small.jpg</picture_url>
      </person>
      <person>
        <role>ICFP'17 General Chair in Steering Committee</role>
        <sort_key>11</sort_key>
        <first_name>Jeremy</first_name>
        <last_name>Gibbons</last_name>
        <affiliation>University of Oxford, UK</affiliation>
        <bio>I am Director of the Software Engineering Programme, which offers part-time professional Masters’ degrees in Software Engineering and in Software and Systems Security. I am currently the Chair of Faculty of Computer Science. For the academic years 2008-2010 was also Deputy Director of the Computing Laboratory (now the Department of Computer Science). I am a fellow of Kellogg College. Before taking up this post in 1999, I held lectureships at Oxford Brookes University and the University of Auckland, New Zealand.</bio>
        <homepage_url>http://www.cs.ox.ac.uk/jeremy.gibbons/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/jeremygibbons/e4e44a9a-31d8-4104-abdc-4a28ecbd8618/small.jpg</picture_url>
      </person>
      <person>
        <role>SIGPLAN Chair in Steering Committee</role>
        <sort_key>12</sort_key>
        <first_name>Michael</first_name>
        <last_name>Hicks</last_name>
        <affiliation>University of Maryland, College Park</affiliation>
        <bio>Michael Hicks is a Professor in the Computer Science department and UMIACS at the University of Maryland, where he co-directs the laboratory for Programming Languages research (PLUM); he is the former Director of the Maryland Cybersecurity Center (MC2). 
His research focuses on using programming languages and analyses to improve the security, reliability, and availability of software. He is perhaps best known for his work exploring dynamic software updating, which is a technique by which software can be updated without shutting it down. He has explored the design of new programming languages and analysis tools for helping programmers find bugs and software vulnerabilities, and for identifying suspicious or incorrect program executions. 
His recent work has combined ideas from PL and cryptography, e.g., to ensure privacy preserving computations. He also leads the development of a new security-oriented programming contest, “build-it, break-it, fix-it,” which has been offered to the public and to students in his Coursera class on software security. He is the co-editor of the Programming Languages Enthusiast blog and Tweets at @michael_w_hicks.</bio>
        <homepage_url>http://www.cs.umd.edu/~mwh/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/michaelhicks/3864a29f-1e96-47cc-9798-bcafe0dd0b04/small.jpg</picture_url>
      </person>
      <person>
        <role>Mobile App Chair in Organizing Committee</role>
        <sort_key>13</sort_key>
        <first_name>Reid</first_name>
        <last_name>Holmes</last_name>
        <affiliation>University of Waterloo</affiliation>
        <bio>undefined</bio>
      </person>
      <person>
        <role>Member at large in Steering Committee</role>
        <sort_key>14</sort_key>
        <first_name>John</first_name>
        <last_name>Hughes</last_name>
        <affiliation>Chalmers University of Technology</affiliation>
        <bio>R. John M. Hughes (born ca 1958) is a Swedish computer scientist and professor in the department of Computing Science at the Chalmers University of Technology.
Hughes received his PhD from the University of Oxford in 1984 for the thesis “The Design and Implementation of Programming Languages”.
He is a member of the Functional Programming group at Chalmers, and much of his research relates to the Haskell programming language. He does research in the field of programming languages and is the author of several influential research papers on the subject, including “Why Functional Programming Matters”.[1]
He is also one of the developers of QuickCheck, and cofounder and CEO of QuviQ, which provides the QuickCheck software and offers classes in how to use it.</bio>
        <homepage_url>http://www.cse.chalmers.se/~rjmh/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/johnhughes/3f79ad93-d1b9-44df-92af-0d454dbeae0c/small.jpg</picture_url>
      </person>
      <person>
        <role>ICFP'14 General Chair in Steering Committee</role>
        <sort_key>15</sort_key>
        <first_name>Johan</first_name>
        <last_name>Jeuring</last_name>
        <affiliation>Utrecht University</affiliation>
        <bio>Professor of Software Technology for Learning and Teaching at the Institute of Information and Computing Sciences of Utrecht University (95%), and professor of Software Technology at the School of Computer Science of the Open University (OUNL).
I develop software technology to support learning and teaching, and advanced methods for constructing software.</bio>
        <homepage_url>http://www.staff.science.uu.nl/~jeuri101/homepage/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/johanjeuring/20c79659-6683-4aeb-bd29-3e172bfa3f36/small.jpg</picture_url>
      </person>
      <person>
        <role>ICFP'17 Program Chair in Steering Committee</role>
        <sort_key>16</sort_key>
        <first_name>Mark</first_name>
        <last_name>Jones</last_name>
        <affiliation>Portland State University</affiliation>
        <bio>I am a Professor in the Department of Computer Science in the Maseeh College of Engineering &amp;amp; Computer Science at Portland State University in Portland, Oregon, USA.
My research interests include all aspects of programming language design, implementation, and application. I am particularly interested in the use of advanced programming language technologies for systems programming, and in the development and application of expressive type and module systems that support the construction and certification of secure and reliable software systems.
I am a member of IFIP Working Group 2.8 - Functional Programming.
At various times, I served as a PI for the HASP, Programatica and the Timber projects. (People still ask me about Timbot).
I was the original designer and implementor of the Gofer and Hugs systems. But, after ten years’ work, I no longer maintain or develop those systems.
I live and work in Oregon in the USA. You’d like it here too …</bio>
        <homepage_url>http://web.cecs.pdx.edu/~mpj/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/markjones/cdebe836-fdeb-4fb5-9f2d-181462ee49cf/small.jpg</picture_url>
      </person>
      <person>
        <role>Local Organizer co-Chair in Organizing Committee</role>
        <sort_key>17</sort_key>
        <first_name>Shin-ya</first_name>
        <last_name>Katsumata</last_name>
        <affiliation>Kyoto University, Japan</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.kurims.kyoto-u.ac.jp/~sinya/index-e.html</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/shinyakatsumata/5e61dcb3-bb87-442b-bbd6-0f9a566f939d/small.jpg</picture_url>
      </person>
      <person>
        <role>General Co-Chair in Organizing Committee, ICFP'16 General Chair in Steering Committee</role>
        <sort_key>18</sort_key>
        <first_name>Gabriele</first_name>
        <last_name>Keller</last_name>
        <affiliation>University of New South Wales</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://www.cse.unsw.edu.au/~keller/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/gabrielekeller/6d6ca9ff-4423-4136-9776-43f25bd5ac29/small.jpg</picture_url>
      </person>
      <person>
        <role>Publicity chair in Organizing Committee, Publicity chair in Steering Committee</role>
        <sort_key>19</sort_key>
        <first_name>Lindsey</first_name>
        <last_name>Kuper</last_name>
        <affiliation>Intel Labs</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.indiana.edu/~lkuper/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/lindseykuper/eceeaffb-2748-4078-aaf9-31e603ef1b68/small.jpg</picture_url>
      </person>
      <person>
        <role>Workshops Co-Chair in Organizing Committee</role>
        <sort_key>20</sort_key>
        <first_name>Andres</first_name>
        <last_name>Löh</last_name>
        <affiliation>Well-Typed LLP</affiliation>
        <bio>Since 2010, I am a partner and Haskell Consultant at Well-Typed LLP.</bio>
        <homepage_url>http://www.andres-loeh.de/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/andresloh/d7276ea5-1b0c-4d50-9ffb-6cadab33f624/small.jpg</picture_url>
      </person>
      <person>
        <role>Member at large in Steering Committee</role>
        <sort_key>21</sort_key>
        <first_name>Yaron</first_name>
        <last_name>Minsky</last_name>
        <affiliation>Jane Street</affiliation>
        <bio>undefined</bio>
        <picture_url>http://conf.researchr.org/getProfileImage/yaronminsky/4b00b8d8-8a54-452b-b11c-e7c269d64554/small.jpg</picture_url>
      </person>
      <person>
        <role>Programming Contest Organiser in Organizing Committee</role>
        <sort_key>22</sort_key>
        <first_name>Keisuke</first_name>
        <last_name>Nakano</last_name>
        <affiliation>The University of Electro-Communications</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://millsmess.cs.uec.ac.jp/~ksk/en/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/keisukenakano/298c7a7e-c06b-489e-9715-cb0a8bba9501/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Volunteer Co-Chair in Organizing Committee</role>
        <sort_key>23</sort_key>
        <first_name>Yuuki</first_name>
        <last_name>Nishida</last_name>
        <affiliation>Kyoto University</affiliation>
        <bio>undefined</bio>
      </person>
      <person>
        <role>Local Organizer co-Chair in Organizing Committee</role>
        <sort_key>24</sort_key>
        <first_name>Susumu</first_name>
        <last_name>Nishimura</last_name>
        <affiliation>Kyoto University</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://www.math.kyoto-u.ac.jp/~susumu/</homepage_url>
      </person>
      <person>
        <role>ICFP'15 Program Chair in Steering Committee</role>
        <sort_key>25</sort_key>
        <first_name>John</first_name>
        <last_name>Reppy</last_name>
        <affiliation>University of Chicago</affiliation>
        <bio>John Reppy has been exploring issues in language design and implementation since the late 1980’s, with a focus on higher-order, typed, functional languages. He is the inventor of Concurrent ML (CML), co-inventor of the Moby programming language, and has made major contributions to the Standard ML of New Jersey system. He is also the co-editor of the the Standard ML Basis Library specification. His current research focus is on the design and implementation of parallel-programming languages as part of the Manticore and Diderot projects.
He received his PhD from Cornell University in 1992 and worked at Bell Laboratories, Murray Hill for eleven years. He is currently a professor of Computer Science and a Senior Fellow of the Computation Institute at the University of Chicago. From August 2011 through August 2013, he served as a Program Director at the National Science Foundation where he helped start the Exploiting Parallelism and Scalability program (XPS).</bio>
        <homepage_url>http://people.cs.uchicago.edu/~jhr/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/johnreppy/7c9e332e-ee11-4f40-82ee-8864028ba80b/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Volunteer Co-Chair in Organizing Committee</role>
        <sort_key>26</sort_key>
        <first_name>Gabriel</first_name>
        <last_name>Scherer</last_name>
        <affiliation>Northeastern University</affiliation>
        <bio>(this profile is inactive, it is a duplicate.)</bio>
        <picture_url>http://conf.researchr.org/getProfileImage/gabrielscherer1/d070028f-9382-4b21-a799-054024c2d718/small.jpg</picture_url>
      </person>
      <person>
        <role>Member at large in Steering Committee</role>
        <sort_key>27</sort_key>
        <first_name>Michael</first_name>
        <last_name>Sperber</last_name>
        <affiliation>Active Group GmbH</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://deinprogramm.de/sperber/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/michaelsperber/e0008500-aa96-40e3-87f9-afe454474878/small.jpg</picture_url>
      </person>
      <person>
        <role>Member at large in Steering Committee</role>
        <sort_key>28</sort_key>
        <first_name>Wouter</first_name>
        <last_name>Swierstra</last_name>
        <affiliation>University of Utrecht</affiliation>
        <bio>After studying Mathematics and Computer Science at the University of Utrecht, I did my PhD under supervision of Thorsten Altenkirch at the University of Nottingham’s Functional Programming Lab. I worked as a post-doc at Chalmers University of Technology, before moving back to the Netherlands to work at Vector Fabrics, a high-tech startup that uses functional programming to facilitate the design of embedded systems. After this brief stint in industry, I returned to academia as a postdoc in the Foundations Group at the Radboud University Nijmegen.</bio>
        <homepage_url>http://www.staff.science.uu.nl/~swier004/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/wouterswierstra/1db000a0-20ed-4c0d-b00c-d467bf461548/small.jpg</picture_url>
      </person>
      <person>
        <role>SIGPLAN Vice Chair in Steering Committee</role>
        <sort_key>29</sort_key>
        <first_name>Peter</first_name>
        <last_name>Thiemann</last_name>
        <affiliation>University of Freiburg, Germany</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www2.informatik.uni-freiburg.de/~thiemann/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/peterthiemann/e05f6038-4b5e-4c38-91bb-a460b5d8d756/small.jpg</picture_url>
      </person>
      <person>
        <role>Industrial Relations Chair in Organizing Committee</role>
        <sort_key>30</sort_key>
        <first_name>Ryan</first_name>
        <last_name>Trinkle</last_name>
        <affiliation>Obsidian Systems LLC</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://obsidian.systems/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/ryantrinkle/8da7a5a4-ba97-4d65-bbad-058f3f5a93dc/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Research Competition Chair in Organizing Committee</role>
        <sort_key>31</sort_key>
        <first_name>David</first_name>
        <last_name>Van Horn</last_name>
        <affiliation>University of Maryland, USA</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://www.cs.umd.edu/~dvanhorn/</homepage_url>
        <picture_url>http://conf.researchr.org/getProfileImage/davidvanhorn/767593d7-5911-4b7b-8895-518920ea97a7/small.jpg</picture_url>
      </person>
      <person>
        <role>Workshops Co-Chair in Organizing Committee</role>
        <sort_key>32</sort_key>
        <first_name>Nicolas</first_name>
        <last_name>Wu</last_name>
        <affiliation>University of Bristol, UK</affiliation>
        <bio>undefined</bio>
        <picture_url>http://conf.researchr.org/getProfileImage/nicolaswu/b942d968-9bf7-4c15-9110-828a9d048664/small.jpg</picture_url>
      </person>
    </persons>
  </event_details>
  <subevent>
    <subevent_id>b1888e72-535c-463c-b850-97c49835dc68</subevent_id>
    <title>Reports: ICFP Program Chair Report and Contest Presentation</title>
    <subevent_type type="regular"/>
    <room>Noh Theater</room>
    <date>2016/09/20</date>
    <url>http://conf.researchr.org/track/icfp-2016/icfp-2016-ICFP-2016-Report</url>
    <url_link_display>Reports</url_link_display>
    <tracks>
      <track>Reports</track>
    </tracks>
    <timeslot>
      <slot_id>2b0d6c3b-d675-4640-a2e9-a0942107f634</slot_id>
      <title>Program Chair Report (Eijiro Sumii)</title>
      <room>Noh Theater</room>
      <date>2016/09/20</date>
      <start_time>17:40</start_time>
      <end_time>17:50</end_time>
      <description>undefined</description>
      <tracks>
        <track>Reports</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>cd30b846-8ae6-44d3-bbc9-a7c36dd97cd0</slot_id>
      <title>Programming Contest Presentation (Keisuke Nakano)</title>
      <room>Noh Theater</room>
      <date>2016/09/20</date>
      <start_time>17:50</start_time>
      <end_time>18:10</end_time>
      <description>undefined</description>
      <tracks>
        <track>Reports</track>
      </tracks>
    </timeslot>
  </subevent>
  <subevent>
    <subevent_id>e769d444-10dc-4eca-b312-0a72943f6025</subevent_id>
    <title>Reports: SRC Awards and Closing</title>
    <subevent_type type="regular"/>
    <room>Noh Theater</room>
    <date>2016/09/21</date>
    <url>http://conf.researchr.org/track/icfp-2016/icfp-2016-ICFP-2016-Report</url>
    <url_link_display>Reports</url_link_display>
    <tracks>
      <track>Reports</track>
    </tracks>
    <timeslot>
      <slot_id>226c2eb1-7e6e-427c-ab21-e9652eec6b09</slot_id>
      <title>SRC Awards (David Van Horn)</title>
      <room>Noh Theater</room>
      <date>2016/09/21</date>
      <start_time>17:40</start_time>
      <end_time>17:55</end_time>
      <description>undefined</description>
      <tracks>
        <track>Reports</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>8f680b79-0b17-4aed-9505-80ac93b403b7</slot_id>
      <title>ICFP 2016 Closing / ICFP 2017 Presentation</title>
      <room>Noh Theater</room>
      <date>2016/09/21</date>
      <start_time>17:55</start_time>
      <end_time>18:10</end_time>
      <description>undefined</description>
      <tracks>
        <track>Reports</track>
      </tracks>
    </timeslot>
  </subevent>
  <subevent>
    <subevent_id>635585e0-020d-498c-978e-c6e023a8af5a</subevent_id>
    <title>Keynote Talks: Keynote 2</title>
    <subevent_type type="regular"/>
    <room>Noh Theater</room>
    <date>2016/09/20</date>
    <url>http://conf.researchr.org/track/icfp-2016/icfp-2016-keynote-talks</url>
    <url_link_display>ICFP 2016 Keynote Talks</url_link_display>
    <tracks>
      <track>ICFP 2016 Keynote Talks</track>
    </tracks>
    <timeslot>
      <slot_id>92f62cbf-1325-4e9f-8759-55be4af4a490</slot_id>
      <title>Journey to Find Bugs in JavaScript Web Applications in the Wild</title>
      <room>Noh Theater</room>
      <date>2016/09/20</date>
      <start_time>09:15</start_time>
      <end_time>10:15</end_time>
      <description>Analyzing real-world JavaScript web applications is a challenging task. On top of understanding the semantics of JavaScript, it requires modeling of web documents, platform objects, and interactions between them. Not only the JavaScript language itself but also its usage patterns are extremely dynamic. JavaScript can generate code and run it during evaluation, and most web applications load JavaScript code dynamically. Such dynamic characteristics of JavaScript web applications make pure static analysis approaches inapplicable.